spring:
  datasource:
    url: ${DATABASE_URL} # Render 或本地 PostgreSQL 的连接URL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

server:
  port: 8080

#spring:
#  datasource:
#    url: ${DATABASE_URL}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect